### PR TITLE
Removed the composer.lock. Libraries shouldn't commit it.

### PR DESCRIPTION
**Pull request by hopeseekr**
It removes the warning:

image

---
This change is [Reviewable](https://reviewable.io/reviews/delight-im/php-i18n/6)

### CODE REVIEW

**Comment by ocram** [comment]
Thanks!

First, that “libraries *shouldn’t* commit it” is not correct.

The official Composer documentation says that [“for libraries it is *not necessary* to commit the lock file”](https://getcomposer.org/doc/01-basic-usage.md#updating-dependencies-to-their-latest-versions), and [“for your library you *may* commit the `composer.lock` file *if you want to*”](https://getcomposer.org/doc/02-libraries.md#lock-file), which [“can help your team to always test against the same dependency versions”](https://getcomposer.org/doc/02-libraries.md#lock-file), which is great and is something that we want.

Apart from that, I’d be really curious what part of the current `composer.lock` may be causing the problems that you describe. What else does the `composer.json` contain in a project that causes this error message to be shown? Is it the platform requirements that cannot be satisfied?

**Comment by hopeseekr** [comment]
@ocram It is missing `        "ext-gettext": "*"`. 

I successfully ran `composer install` on a PHP instance w/o ext-gettext, but it blew up immediately. Removing the `composer.lock` or adding that line fixes it.

**Comment by ocram** [comment]
Thank you!

The `composer.lock` was indeed outdated and thus missing the dependency on `ext-gettext`, which was fixed in [this commit](https://github.com/delight-im/PHP-I18N/commit/af53ba45e88e4d8e8f42946570b6e04c1fc564a4).

Are you suggesting that this was also the cause of the error message stating that “your requirements could not be resolved to an installable set of packages” on install? Doesn’t this usually occur if *too many* (unsatisfiable) dependencies are listed, not too few?

According to the Composer documentation, again, the [“lock file will not have any effect on other projects that depend on”](https://getcomposer.org/doc/02-libraries.md#lock-file) this library.

Did you run `composer install` in a local clone of this project, or in another project that was set up to depend on this library here?

**Comment by hopeseekr** [comment]
It happened to me both places.  It just downright refused with huge long list of error messages I didn't bother to read when I did `composer require`. When I cloned the project, fully intending to help you out w/ your test code coverage, I was saddened that plain old `composer install` didn't work.

Then, i was even more saddened to see that you didn't have a single modern PHP automated testing framework, instead relying on -old- school pre-2005 tests.php. I was even more saddened when it failed to run due to me not having `es-AR`. I doubt many people have the Argentinian Spanish locale installed, at least percentage-wise, in the world. 

It was at that point that I largely gave up and created this PR.

----

I still want to point out that the community seems to largely agree that commiting a composer.lock file is a no-no for libraries. In fact, of the few that do, virtually 90% of them exclude the composer.lock from composer installation, via `.gitattributes`, just to avoid this weird sort of stuff.

See https://stackoverflow.com/a/24247443/430062

Of course, I found this out in a most spectacularly embarassing way when I (naively) thought a few months back that an upstream package had accidentally broken PHPUnit 7.0 support for PHP 7.1. See https://github.com/sebastianbergmann/phpunit/issues/3603 where I was appropriately schooled.

**Comment by ocram** [comment]
Thanks!

Since we can’t reproduce these problems, don’t see any hints that it’s indeed the `composer.lock` that’s causing the error message, have no non-platform dependencies at all, our general experience tells us that committing `composer.lock` does not cause any problems, and the official documentation states so as well, we’re not changing anything for now (until there is any new information).

**Pull request closed without merging**
